### ISSUE TITLE
About TPS method compensation 

### ISSUE THREAD

**Issue by 2653888596** [BingyaoHuang/CompenNet#10]
I really admire the author's work ！

After reading your article, I saw that you used TPS 
as a comparison method. Can you open source the 
code used by TPS on your dataset?
 
And I saw from Issues that you mentioned that TPS uses all 
The shading map of, which makes me feel a little confused, 
your dataset only has the last shading capture image.

Looking forward to your reply, I will be grateful .

**Comment by BingyaoHuang** [comment]
Thank you for the interest :). Currently organizing the TPS code in not on my to-do list, especially when there is already a [TPS python implementation](https://github.com/pjessesco/grundhofer2015) that is compatible with CompenNet dataset. Glad to see that your question is well addressed in https://github.com/pjessesco/grundhofer2015/issues/1.
