### ISSUE TITLE
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by sapoluri** [BingyaoHuang/CompenNet#2]
The execution bails out at the end of the first iteration with the above error:

How to fix it:
everywhere you call <xyz>.to(device) you need to change it to <xyz> = <xyz>.to(device).

The "to" function call isn't modifying the object it's called upon.

**Comment by BingyaoHuang** [comment]
Thank you. Fixed in [76f2896](https://github.com/BingyaoHuang/CompenNet/commit/76f28961cd41136094eb63ce4eca163bfe673e53).
