### ISSUE TITLE
When using pretrained model execution fails

### ISSUE THREAD

**Issue by sapoluri** [BingyaoHuang/CompenNet#3]
File "main.py", line 172, in <module>
    compen_net.module.name = model_name
  File "/home/spoluri/cm/CompenNet/virtual_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'CompenNet' object has no attribute 'module'

Solution:
Remove module from line 172 and it should look like this: compenNet.name = model_name

**Comment by BingyaoHuang** [comment]
Thank you. Fixed in [24f3afd](https://github.com/BingyaoHuang/CompenNet/commit/24f3afd2cf5cee5ded47092954dbe2fb51d00b52).
